[package]
name = "byte-mutator"
version = "0.1.0"
authors = ["ragona <ryanragona@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"
